# version: "3.9"

volumes:
  db-data-v2:
  cache-v2:

networks:
  webscraper-net-v2:

services:
  db:
    image: postgres:15.8
    container_name: webscraper-v2-postgres
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - db-data-v2:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: $WEBSCRAPER_DB_HOST
      POSTGRES_DB: $WEBSCRAPER_DB_NAME
      POSTGRES_USER: $WEBSCRAPER_DB_USER
      POSTGRES_PASSWORD: $WEBSCRAPER_DB_PASSWORD
    networks:
      - webscraper-net-v2

  webscraper:
    restart: always
    container_name: webscraper-v2
    volumes:
      - ./media:/web_app_v2/amazon/media/
      - ./static:/web_app_v2/amazon/static/
      - ./amazon:/web_app_v2/amazon
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8016:8009"
    env_file:
      - .env
    networks:
      - webscraper-net-v2

  celery:
    image: webscraper-v2
    command: "celery -A amazon.webscraper.celery worker --loglevel=info"
    restart: always
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - webscraper-net-v2

  celerybeat:
    image: webscraper-v2
    restart: always
    command: "celery -A amazon.webscraper.celery beat --loglevel=info"
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - webscraper-net-v2

  redis:
    image: redis
    container_name: webscraper-v2-redis
    restart: always
    volumes:
      - cache-v2:/data
    expose:
      - "6382:6380"
    networks:
      - webscraper-net-v2
