# Generated by Django 4.1.2 on 2022-11-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvertisingMonitoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("seller_name", models.CharField(max_length=64)),
                ("product_name", models.CharField(max_length=64)),
                ("frequency", models.IntegerField()),
                ("google_sheet_link", models.URLField()),
                ("asins", models.CharField(max_length=255)),
                ("target_acos", models.IntegerField()),
                ("entity_id", models.CharField(max_length=32)),
                ("login", models.CharField(max_length=64)),
                ("password", models.CharField(max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AsinsMonitoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("seller_name", models.CharField(max_length=64)),
                ("product_name", models.CharField(max_length=64)),
                ("frequency", models.IntegerField()),
                ("google_sheet_link", models.URLField()),
                ("personal_asin", models.CharField(max_length=10)),
                ("competitor_asins", models.CharField(max_length=100)),
                ("keywords", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
