# Generated by Django 4.1.2 on 2022-12-03 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingmonitoring',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 3, 54, 3, 304862, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asinsmonitoring',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 3, 54, 11, 803661, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
