# Generated by Django 4.1.2 on 2022-12-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0002_advertisingmonitoring_last_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asinsmonitoring',
            name='keywords',
            field=models.TextField(),
        ),
    ]
