# Generated by Django 4.1.2 on 2023-01-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_alter_asinsmonitoring_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='asinsmonitoring',
            name='base_url',
            field=models.URLField(default='https://amazon.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asinsmonitoring',
            name='country_cookie',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
