# Generated by Django 4.2.8 on 2024-07-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webscraper", "0004_asinsmonitoring_base_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
