# Generated by Django 4.1.2 on 2024-10-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0005_added_new_campaign_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
