# Generated by Django 4.1.2 on 2024-10-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0006_campaign_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
